### ISSUE TITLE
ReResolving leads to parse errors when called by multiple processes

### ISSUE THREAD

**Issue by Guoanshisb** [boogie-org/corral#10]
https://github.com/boogie-org/corral/blob/e20a0704670b54ea0c17da9182f4ebf6be7cb543/source/Util/BoogieUtil.cs#L444-L447

`ReResolve` function writes the program to a file with a fixed name. Errors could occur when multiple threads are calling this function.

**Comment by akashlal** [comment]
That's right. It is not thread safe. But its not just about writing the same file to disk, even the Boogie parser is not thread safe. Correct synchronization is up to the user. Are you hitting a bug because of this?

**Comment by Guoanshisb** [comment]
@akashlal I was trying to set up lit for regression test and parsing errors in `temp_rar.bpl`occur when multiple examples ran concurrently. These errors seem to come from this function used by SmackInst. I was able to get rid of them by changing the file path to a unique id under a temporary folder.

**Comment by akashlal** [comment]
Ah, you don't mean thread-safe, you mean more like "process-safe". The other fix is to use ReResolveInMem, which doesn't go to disk.

**Comment by Guoanshisb** [comment]
@akashlal I see. Thanks. I'll update SmackInst using `ReResolveInMem`.

**Comment by akashlal** [comment]
Great

**Comment by Guoanshisb** [comment]
@akashlal It seems that I still got parse errors using `ReResolveInMem`. I had to change the filename string passing to `Parser` to get rid of the errors.

**Comment by akashlal** [comment]
@Guoanshisb This can't be. The filename argument to Parser.Parse is only used for debugging output. It has nothing to do with an actual file on the disk. You must be getting the error for some other reason.

**Comment by Guoanshisb** [comment]
@akashlal You are right. I got the error because `ReResolve` is also used by `AvHarnessInstrumentation`. Is there a particular reason that it is used rather than `ReResolveInMem`?

**Comment by akashlal** [comment]
@Guoanshisb Your commit looks good. If you're satisfied, please close this issue.
