### ISSUE TITLE
Nonlinear arithmetic incompleteness?

### ISSUE THREAD

**Issue by prgantonino** [boogie-org/corral#100]
Hi,

Thanks again for such a great tool!

The assertion in the following code is not passing, although I believe it should. It seems as if the line " ir := ir mod ir;" in the procedure f is not taking effect. I am not sure why is that: whether it could be a bug in corral or simply some incompleteness of the underlying solver. I believe it is the latter but, on the off chance it could be the former, I thought I might as well report it.

Thanks again!

procedure main () returns ()
{
    var ret : int;
    call ret := f(10);
    call {:cexpr "ret"} boogie_si_recordi(ret);
    assert (ret == 0);
}

procedure boogie_si_recordi (i : int) returns ();

procedure f (i : int) returns (r : int)
{
    var ir : int;
    ir := (i * i);
    ir := ir mod ir;
    r := ir;
    return;
}

**Comment by akashlal** [comment]
@prgantonino, happy to hear that you like corral! 

I took this program and ran corral as `corral.exe foo.bpl /main:main` and it returned `Program has no bugs`. Are you getting something else? 

In general, incompleteness in Z3 can mean that corral will return false bugs. In your particular case, it is up to Z3 to prove that `(10 * 10) mod 10 == 0` using its theories for multiplication and `mod`.

**Comment by pedrotbtl** [comment]
I am running corral with Z3 version 4.7.1 - 64 bit.
I ran: "mono ~/Tools/corral-master/corral/bin/Release/corral.exe ~/testMod.bpl /recursionBound:20 /main:main /printDataValues:1"

And as a result I got:

Single threaded program detected
Verifying program while tracking: {assertsPassed}
Program has a potential bug: True bug
PersistentProgram(12,1): error PF5001: This assertion can fail

/homedir/testMod.bpl(6,1): error PF5001: This assertion can fail

Execution trace:
Format: (tid,k)  filename(line,col): blockName   (extra info)
(1,0)    /homedir/testMod.bpl(4,1): anon0  
(1,0)    /homedir/testMod.bpl(4,1): anon0  (CALL f)
(1,0)     /homedir/testMod.bpl(14,4): anon0  
(1,0)     /homedir/testMod.bpl(14,4): anon0  
(1,0)     /homedir/testMod.bpl(15,4): anon0  
(1,0)     /homedir/testMod.bpl(16,3): anon0  
(1,0)    /homedir/testMod.bpl(4,1): anon0  (RETURN from f )
(1,0)    /homedir/testMod.bpl(5,1): anon0  (ret = 100)
(1,0)    /homedir/testMod.bpl(6,1): anon0  (ASSERTION FAILS assert ret == 0;
 )
(1,0)    /homedir/testMod.bpl(6,1): anon0  (Done)

Boogie verification time: 0.18 s
Time spent reading-writing programs: 0.02 s

Time spent checking a program (1): 0.22 s
Time spent checking a path (1): 0.07 s

Number of procedures inlined: 2
Number of variables tracked: 1
Total Time: 0.460392 s
Total User CPU time: 0.483415 s

Number of procedures inlined: 2
Number of variables tracked: 1
Total Time: 0.460392 s
Total User CPU time: 0.483415 s

**Comment by akashlal** [comment]
It is probably to do with the Z3 version. I was using `Z3 version 4.8.5 - 64 bit`. I would expect that deciding non-linear arithmetic is incomplete. Perhaps my version just got lucky.

**Comment by zvonimir** [comment]
We are seeing lots of incompleteness issues in the presence of non-linear arithmetic when using Z3 version 4.8.7. They seem to be under control in the nightly build of Z3, and so hopefully lots of them will be resolved with the next release.
So I am closing this.
