### ISSUE TITLE
AV: Smack generated bpls needs to add "partition" to assumes from conditions?

### ISSUE THREAD

**Issue by shuvendu-lahiri** [boogie-org/corral#11]
EE seems to skip any assume that does not have "partition" attribute. None of the EE heuristics/traceSlicing will be needed in this case. 

````        
 private static bool MatchesSyntacticAssumeFilters(AssumeCmd assumeCmd)
        {
            if (((AssumeCmd) assumeCmd).Expr.ToString() == Expr.True.ToString()) return false;
            //only consider assume wiht {:partition} tags
            if (!QKeyValue.FindBoolAttribute(assumeCmd.Attributes, "partition")) return false;
            if (ignoreAllAssumes) return false;
            if(onlySlicAssumes) return QKeyValue.FindBoolAttribute(assumeCmd.Attributes, "slic");
            return true;
        }
````

**Comment by akashlal** [comment]
I think there are two parts here.
1. The compiler should be able to tell which assumes are branches in the code (as opposed to some other instrumented assumes).
2. EE should not have these implicit flags. All of them should be lifted out, even move to Alex's config language.

**Comment by shuvendu-lahiri** [comment]
Agree. For (2), we need to establish the "default" behavior of EE in the absence of any flags. Issue similar to #8.

**Comment by shuvendu-lahiri** [comment]
Shaobo: can I close this issue?
