### ISSUE TITLE
use of assume forall in corral

### ISSUE THREAD

**Issue by muyaview** [boogie-org/corral#112]
Hi, 
For below boogie codes:
```c
var M1: [int]int;
var M2: [int]int;

procedure {:entrypoint} main()
  modifies M1,M2;
{
    var n : int;

    M1[0] := 1;
    M1[1] := 1;
    M1[2] := 1;
    M1[3] := 0;
    M1[4] := 0;

    M2[0] := 1;
    M2[1] := 1;
    M2[2] := 1;
    M2[3] := 1;
    M2[4] := 1;

    assume n >= 0 && n < 5;
    assume M1[n] != M2[n];
    assume (forall i : int :: i >=0 && i < n ==> M1[i] == M2[i]);

    assert n == 3 ;
}
```
`n` is supposed to equals to `3`. But the result is like below:
```
Verifying program while tracking: {assertsPassed}
Program has a potential bug: True bug
PersistentProgram(28,1): error PF5001: This assertion can fail

001.bpl(25,1): error PF5001: This assertion can fail

Execution trace:
Format: (tid,k)  filename(line,col): blockName   (extra info)
(1,0)    001.bpl(9,11): anon0
(1,0)    001.bpl(9,11): anon0
(1,0)    001.bpl(10,11): anon0
(1,0)    001.bpl(11,11): anon0
(1,0)    001.bpl(12,11): anon0
(1,0)    001.bpl(13,11): anon0
(1,0)    001.bpl(15,11): anon0
(1,0)    001.bpl(16,11): anon0
(1,0)    001.bpl(17,11): anon0
(1,0)    001.bpl(18,11): anon0
(1,0)    001.bpl(19,11): anon0
(1,0)    001.bpl(21,5): anon0
(1,0)    001.bpl(22,5): anon0
(1,0)    001.bpl(23,5): anon0
(1,0)    001.bpl(25,5): anon0  (ASSERTION FAILS assert n == 3;
 )
(1,0)    001.bpl(25,5): anon0  (Done)

```
However, the verification would be passed if I replace `assert n==3` to `assert n ==3 || n==4)`. 
Seems the statement in line NO. 23 is not working. If I remove this line of code, the result is same. 
Please help on this. Many thanks

**Comment by akashlal** [comment]
Reasoning with quantifiers in Corral is incomplete by default. (The same is true for Boogie and Z3 as well). This means that Corral can say `assertion can fail` when it indeed cannot fail. In your example, Corral is unable to reason about the `assume forall`. You can try writing that line as a loop instead and then supply a recursion bound (say, `/recursionBound:5`) on the command line. Then Corral's reasoning will be complete (up to the given recursion bound).

**Comment by muyaview** [comment]
Many thanks Akash for your explaination. 

I tried to run corral with the parameter `/useArrayTheory` for same example. Corral didn't report the assertion failure any more. 
I this case, does this mean corral have some special logic for `map` to make sure the complete?

**Comment by zvonimir** [comment]
In general, Corral is typically more complete when it uses the theory of arrays. So this is what it relies on by default. I hope this helps. I'll close this issue, and please reopen it if you have more questions.
