### ISSUE TITLE
Corral doesn't support polymorphic type constructor

### ISSUE THREAD

**Issue by Invincibleyc** [boogie-org/corral#117]
I wrote the following program.
```
type Ref;
type Field T;
type HeapType = <T>[Ref, Field T]T;
var Heap:HeapType;
type macAddr_t = bv48;

// Struct headers
const unique headers.ethernet:Field Ref;
const unique headers.ipv4:Field Ref;

// Header ethernet_t;
const unique ethernet_t.dstAddr:Field macAddr_t;

var instance:Ref;

procedure main()
modifies Heap;
{
	Heap[Heap[instance, headers.ethernet], ethernet_t.dstAddr]:=2bv48;
	assert(1+1==3);
}
```

Boogie reports an assertion violation.
```
Boogie program verifier version 2.4.1.10503, Copyright (c) 2003-2014, Microsoft.
heap.bpl(20,2): Error BP5001: This assertion might not hold.
Execution trace:
    heap.bpl(19,60): anon0

Boogie program verifier finished with 0 verified, 1 error
```

But Corral reports the following error.
```
Corral program verifier version 1.0.0.0
Warning: Using default recursion bound of 1
Single threaded program detected
Verifying program while tracking: {assertsPassed}
Program has a potential bug: Prover error: line 42 column 101: domain sort T@Field Ref and parameter T@Field T do not match
Corral encountered a prover error. Giving up.
```

**Comment by zvonimir** [comment]
I don't know Corral super well, but I think it does not support polymorphism. If you look at the source code of Corral, it by default uses `/useArrayTheory` switch for Boogie, which I believe turns on `/monomorphize` in Boogie.

This is also a relevant thread to keep an eye on: https://github.com/boogie-org/boogie/issues/195

I hope this helps.

**Comment by Invincibleyc** [comment]
Thanks a lot for replying.
Then I have to think of other ways to encode heaps. It's a little inconvenient.

**Comment by akashlal** [comment]
@Invincibleyc You can look at [this paper](http://cs.ioc.ee/etaps12/localproc/bytecode/paper2.pdf) for an alternative encoding for a program heap. No one has really wanted polymorphism with corral before. Might not be that hard to support. Not sure.
