### ISSUE TITLE
Abstract Houdini removed from Boogie

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/corral#127]
This commit removes abstract Houdini from Boogie source: https://github.com/boogie-org/boogie/commit/8cedb9fe8585dd4aee5d28b503c69f89ed5d9dd6#diff-6c0cfd6dfe16855752b8707ddda8e2b8

I've been working on updating Boogie in Corral, and Corral has dependencies on abstract Houdini that I am not able to untangle.

Is abstract Houdini an important ingredient of Corral?
In that case maybe we should revert the above commit that removes it.

Any suggestions for how to proceed would be welcome. Thanks!

**Comment by zvonimir** [comment]
@akashlal your help would be appreciated here. Thx!

**Comment by zvonimir** [comment]
@akashlal , @shuvendu-lahiri any feedback on this one?
Boogie is moving ahead, and I would like to avoid that Corral falls way behind.
Thanks!

**Comment by akashlal** [comment]
We will have to remove AbsHoudini from Corral as well. I can take care of it.

**Comment by akashlal** [comment]
Done via 9b11c40

**Comment by zvonimir** [comment]
Thanks @akashlal! Your commit resolved that problem, and I just created a pull request that updates Corral to the latest Boogie.
