### ISSUE TITLE
Using Boogie nuget

### ISSUE THREAD

**Issue by akashlal** [boogie-org/corral#130]
Currently Boogie is included as a submodule. Instead, I would like to pull in Boogie binaries as a Nuget. It will speed up the build. In early days, it was useful to have Boogie code included in the same project because Corral integrates so tightly with Boogie APIs. But perhaps that is not needed any more. Unless I hear objections, I will do the switch in a few days.

**Comment by michael-emmi** [comment]
👍 this seems much better

**Comment by zvonimir** [comment]
This makes sense to me as well. Thanks!

**Comment by akashlal** [comment]
Done via 3c7f767f85e81d7744353908c9c95daa541bc8f2
