### ISSUE TITLE
"Turning off Z3 search due to parallel assignments" message meaning?

### ISSUE THREAD

**Issue by hayley-leblanc** [boogie-org/corral#135]
Hi,

I'm using Corral to verify some C code that has been translated into Boogie IVL using SMACK. I've had Corral print out the message "Turning off Z3 search due to parallel assignments" a few times and I can't tell exactly what it means or what's causing it. It seems to be triggered by adding assertions in certain places in my code, although I can't find a pattern between the code locations that trigger it. The Boogie generated from a program that does not print this message, and the same program with an extra assertion that does trigger it, is just the presence of that assertion. 

What exactly does this message mean? Corral seems to sometimes miss bugs in my code when this problem occurs, so I want to figure out how to avoid triggering it. 

Thanks!

**Comment by akashlal** [comment]
A parallel assignment means that the input BPL has an assignment of the form:
```
x, y := e1, e2;
```
This has an impact on the algorithm used to do variable abstraction refinement, the part that selects what additional variables to track. There are two different refinement algorithms, one faster and one slower. I was too lazy to support parallel assignments in the faster algorithm, so instead I fall back to the slower one. The algorithms should both give an acceptable answer, so it should not lead to missing a bug. If your programs are small enough, you can use the flag `/trackAllVars` and not have to worry about variable abstraction at all. A parallel assignment can also be removed as follows:
```
t1 := e1; // new local variable
t2 := e2; // new local variable
x := t1;
y := t2;
```

**Comment by hayley-leblanc** [comment]
Gotcha. Thanks for your help!
