### ISSUE TITLE
Duality / FixedPointVC regressions

### ISSUE THREAD

**Issue by akashlal** [boogie-org/corral#136]
Does anyone use the duality algorithm (that invokes FixedPointVC generation in Boogie)? If not, we should remove it. There are no regressions, so its likely in a broken state already.
@shuvendu-lahiri @zvonimir @shaobo-he @michael-emmi @kenmcmil

**Comment by zvonimir** [comment]
Nobody uses it as far as I know. I would guess it is unlikely that it is still working properly given that it hasn't been maintained for years now, as far as I know.

**Comment by kenmcmil** [comment]
I'm not using that code and I don't know anyone who is. On the other hand, if there is no other path available from boogie to CHC solvers, perhaps it would be good to keep the code and just disable it, so someone could revive it later rather than having to start from scratch.

**Comment by shuvendu-lahiri** [comment]
I like Ken's proposal to keep the code around disabled.

Shuvendu

**Comment by akashlal** [comment]
The history keeps the code around. The question is if keeping the code in "it compiles" state useful or does it just slow things down. Nonetheless, I will keep this issue open for now. I would request someone to contribute corral regressions that test the `/duality` flag, even if the current results are incorrect.  (Should be easy.)

**Comment by shazqadeer** [comment]
Adding @RustanLeino, @bkragl.

**Comment by shazqadeer** [comment]
In the Boogie repo, there are  three files that are pertinent to FixedpointVC: FixedpointVC.cs, RPFP.cs, and ExprExtensions.cs. The code seems useful and I am happy to maintain it provided I can understand what it is doing.  I do agree with @akashlal that it is silly to keep the code around without having any tests for it whatsoever.  So, I think tests should be added for it in Corral.  Independently, I will study the code and do a code review with @kenmcmil in case I run into things I do not understand.

To get a basic understanding of the code, a few questions:

- Is the code supposed to work with standard SMT solvers, like Z3 or CVC4? Boogie targets SMTLIB2 so in principle any SMT solver can be targeted.  @kenmcmil mentioned "CHC solver"; perhaps that is a subset of SMT solvers that should be targeted in case FixedpointVC is used.

- I noticed on line 3024 of ProverInterface.cs:
SendThisVC("(compute-interpolant " + A_str + " " + B_str + ")");
Is compute-interpolant the command that is understood by CHC solvers?

**Comment by akashlal** [comment]
I see that there is a Boogie flag for invoking FixedPointVC directly from boogie:
```
  /fixedPointEngine:<engine>
                Use the specified fixed point engine for inference
```
I think we can also add tests at the Boogie level itself, in case this option does not depend on the "decoration" that corral provides.

**Comment by kenmcmil** [comment]
My recollection is that the interface to solvers is through the SMTLIB2 "horn" logic introduced in Z3. I think it ought to be compatible with the CHC-COMP format. However, the counter-proofs (ie., the ground derivations that act as counterexamples to model checking problems) are probably only compatible with Z3. I'm not sure if CHC-COMP has a standard for output. Since Duality is no longer in Z3, you will probably need to put "spacer" as the argument of "/fixedPointEngine", but I'm not sure about that. Also, the boogie files will need to have and entry procedure declared.  

The compute-interpolant command was an SMTLIB2 command in Z3, but it was removed with the interpolation code. I don't think this is needed for "fixedPointEngine".

**Comment by shazqadeer** [comment]
I just examined the occurrences of `CommandLineOptions.Clo.FixedPointEngine` in the Boogie  codebase. The string value of this field is only ever compared against null, i.e., its value isn't actually used to populate any command.  So putting "spacer" as the argument to /fixedPointEngine is unlikely to have any effect.

Based on what I have heard from @kenmcmil and what I am seeing in the Boogie code, I am discouraged.  The code in Boogie related to CHC stuff is hopelessly outdated.  Modest effort is unlikely to allow us to get a few regression tests running on the code.  I am not prepared to keep the code in Boogie unless we have a few regression tests.

I also tried to educate myself about Spacer by searching on the web. I discovered that Spacer is a tool built off of a fork of Z3 and maintained by Arie Gurfinkel. The fork seems to have happened in 2015 but I saw commits in Spacer as late as 2019.  Spacer has also won some editions of CHC-COMP. I suppose this is the tool that should be targeted by an updated "fixedPointEngine" code in Boogie.

**Comment by kenmcmil** [comment]
My impression was that Spacer is now the default CHC engine in Z3. But anyway, if the the effort to get the code running again seems large, perhaps it should be deleted. I am not going to have much time available to put into it.

**Comment by akashlal** [comment]
Doing `(set-logic HORN)` turns on CHC solving in Z3. However, the Boogie code would require quite some work to target the latest z3. There are several commands that are not supported any more: `(fixpoint-push)`, `(fixpoint-pop)` and `(query ...)`. The work seems non-trivial and since we don't have any takers right now, I recommend that we create a tag and move ahead with removing the code from both Boogie and Corral.

**Comment by shazqadeer** [comment]
Ok, I will work on tag and drop on the Boogie side.
