### ISSUE TITLE
Values not printed in C error trace

### ISSUE THREAD

**Issue by Guoanshisb** [boogie-org/corral#14]
For the bpl file attached, Corral did not print concrete values of expressions passed to `boogie_si_*` calls. Corral prints the following C error trace,
```Boogie
Execution trace:
/usr/local/share/smack/lib/smack.c(1031,3): Trace: Thread=1
/usr/local/share/smack/lib/smack.c(1032,1): Trace: Thread=1
simple_fail.c(12,3): Trace: Thread=1
simple_fail.c(12,3): Trace: Thread=1  (CALL __VERIFIER_assert)
/usr/local/share/smack/lib/smack.c(97,3): Trace: Thread=1
/usr/local/share/smack/lib/smack.c(36,21): Trace: Thread=1
/usr/local/share/smack/lib/smack.c(36,21): Trace: Thread=1  (ASSERTION FAILS assert x != $0;
 )
simple_fail.c(12,3): Trace: Thread=1  (RETURN from __VERIFIER_assert )
simple_fail.c(12,3): Trace: Thread=1  (Done)
```
Arguments passed to Corral are, ` /tryCTrace /noTraceOnDisk /printDataValues:1 /k:1 /useProverEvaluate /timeLimit:1200 /cex:1 /maxStaticLoopBound:1 /recursionBound:1`
[simple_fail.zip](https://github.com/boogie-org/corral/files/263721/simple_fail.zip)

**Comment by akashlal** [comment]
Done. It isn't very pretty, but all data values should now be printed on console.

**Comment by akashlal** [comment]
Closing #14. @Guoanshisb Let me know if this issue isn't resolved on your end.
