### ISSUE TITLE
bogus PRs

### ISSUE THREAD

**Issue by akashlal** [boogie-org/corral#148]
We've started getting some bogus PRs like #146, #147, etc. Almost one per day. Any one have an idea why this is happening? Is it just spam, or is it somehow trying to hack the build pipeline (which I believe is run automatically on each PR)? @boogie-org/corral-devs @boogie-org/boogie-developers

**Comment by siddharth-krishna** [comment]
If you look at the `yml` file the PR is adding, it creates a GitHub action/workflow that downloads some cryptocurrency mining code from https://github.com/xmrig/xmrig...

**Comment by akashlal** [comment]
Thanks for the explanation. Good to keep aware about modern day spam. I'm assuming its not harmful unless the PR gets merged ...

**Comment by cpitclaudel** [comment]
We turned off "new user" contributions on some of our new MIT repos to prevent this, and we made a report to Github support.

**Comment by akashlal** [comment]
@cpitclaudel I don't see any option of turning off new user contributions. Can you help me locate it? The spam continues. ...

**Comment by pdeligia** [comment]
Just turned this off under the "Interaction limits", this seems to be for up to 6 months (what I chose), not sure if there is a better (more permanent) way though...

**Comment by cpitclaudel** [comment]
I'm hoping MS will find a way to resolve this issue site-wide, since limiting interaction isn't ideal.

**Comment by cpitclaudel** [comment]
https://github.blog/2021-04-22-github-actions-update-helping-maintainers-combat-bad-actors/

**Comment by pdeligia** [comment]
Nice, this is timely!
