### ISSUE TITLE
Cannot set nuget key for automatic deployment

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/corral#156]
I tried using the organization key that is associated with boogie-org, but that is not working for some reason. I don't have permissions for nuget packages to be able to do anything about it. I guess maybe we need to generate a new key?

@shazqadeer I would appreciate your help with this since I am stuck at this point. Thanks!

**Comment by zvonimir** [comment]
FYI, if you go here: https://github.com/organizations/boogie-org/settings/secrets/actions
You should be able to see that I enabled the org-level nuget key for corral repo as well.
So at this point I am wondering if something has to be done on the nuget side, which I don't have permissions for.

**Comment by shazqadeer** [comment]
@michael-emmi, @bkragl  :  Any idea?  You likely know the most about automatic package deployment on nuget.

**Comment by shazqadeer** [comment]
@zvonimir : What is the problem you are facing now?   Does the automatic nuget deployment in the CI flow not work?

**Comment by zvonimir** [comment]
Yes. Automatic deployment to nuget fails with a message saying "your nuget
key is wrong".
You can look up the message in the last Corral CI run.

**Comment by shazqadeer** [comment]
I logged into nuget.org and associated NUGET_API_KEY with all packages listed there, including all the Boogie packages and Corral.  Then I updated the tag and pushed and it looks like a nuget package for Corral has been pushed.

@zvonimir :  I noticed that in the package build instructions for Corral, we have the following command:
git push --atomic origin master vx.y.z

This command is different from the one for Boogie.  If you think this is a superior command, please update the Boogie instructions also.

**Comment by zvonimir** [comment]
Great! Yeah, this worked. Thanks a lot @shazqadeer!

Well, my understanding is that without this new push command, you have to do both `push` and `push --tags` since the later one does not push commits, just tags. The new command combines these two into one. I'll do the update on the Boogie side as well.

**Comment by zvonimir** [comment]
I implemented a different solution for pushing releases out. I think it is slightly better when you are doing periodic manual releases (and not doing a release with every push). This is the main commit that does it :https://github.com/boogie-org/corral/commit/fa85ed64b27cd93d48720ff7c0848030452058df
A nice thing about it (I think at least) is that the version is not stored anywhere locally, and so you don't have to to a separate "update version" commit. You just create a tag while doing a github release, and the version gets automatically picked up from the tag.
Another nice thing is that the github releases match nuget releases. Anyhow, if you want to switch Boogie to this, it should be easy.
