### ISSUE TITLE
AV: sdv format trace does not show sliced path

### ISSUE THREAD

**Issue by Guoanshisb** [boogie-org/corral#20]
Each line in sdv format error trace is irrelevant.

To reproduce this issue,
`$(AddOns/AngelicVerifierNull/test/c-smack): python runtest.py t23.bpl --verifier-options="/sdv"`

Rename Angelic0.tt to defect.tt and run trace viewer.

**Comment by shuvendu-lahiri** [comment]
Duplicate of #8

**Comment by shuvendu-lahiri** [comment]
@Guoanshisb can you add the exact command line for avn.exe generated from the log for me to repro.

**Comment by Guoanshisb** [comment]
@shuvendu-lahiri The command line I'm using is `AngelicVerifierNull.exe t23.harness.bpl /nodup /traceSlicing /copt:recursionBound:5 /copt:k:1 /copt:tryCTrace /sdv`

**Comment by Guoanshisb** [comment]
will close after testing with sdvdefect.exe viewer with highlighting.
