### ISSUE TITLE
Unable to build SmackInst.sln

### ISSUE THREAD

**Issue by shuvendu-lahiri** [boogie-org/corral#23]
present in AddOns\SmackInst, and needed by AddOns\AngelicVerifierNull\test\c-smack\runbpl.bat. 

Build fails with 

Error	62	The type 'Microsoft.Boogie.StandardVisitor' is defined in an assembly that is not referenced. You must add a reference to assembly 'BoogieCore, Version=2.3.0.61016, Culture=neutral, PublicKeyToken=736440c9b414ea16'.	E:\corral-github\AddOns\SmackInst\SmackInst\Program.cs	520	18	SmackInst
Error	54	The type or namespace name 'AssertCmd' could not be found (are you missing a using directive or an assembly reference?)	E:\corral-github\AddOns\SmackInst\SmackInst\Program.cs	449	9	SmackInst
Error	61	The type or namespace name 'AssignCmd' could not be found (are you missing a using directive or an assembly reference?)	E:\corral-github\AddOns\SmackInst\SmackInst\Program.cs	495	27	SmackInst
Error	59	The type or namespace name 'AssumeCmd' could not be found (are you missing a using directive or an assembly reference?)	E:\corral-github\AddOns\SmackInst\SmackInst\Program.cs
.....

**Comment by akashlal** [comment]
Done. Please check.

**Comment by shuvendu-lahiri** [comment]
Still need to run updateBoogie.bat ..\boogie\binaries from top-level folder. But closing.
