### ISSUE TITLE
AV: fastavn: print stats when times out?

### ISSUE THREAD

**Issue by shaobo-he** [boogie-org/corral#59]
When fastavn hits the time limit, it just merges the bugs while doesn't print stats as it exits normally. I was wondering if we should let fastavn print stats also in this case so that we could better analyze the results.

**Comment by shuvendu-lahiri** [comment]
Sure. Can you please add it Shaobo?

**Comment by zvonimir** [comment]
I am guessing nobody will work on this any time soon, if ever.
@shuvendu-lahiri and @akashlal : are you ok if I mark this as "won't fix" and close the issue?

**Comment by shuvendu-lahiri** [comment]
Sure.
