### ISSUE TITLE
Continuous integration for Corral

### ISSUE THREAD

**Issue by shaobo-he** [boogie-org/corral#6]
We should take advantage of this cool feature of Github.

**Comment by zvonimir** [comment]
@Guoanshisb : Do you mean "continuous integration"? Also, please write better descriptions for issues you report.

**Comment by Guoanshisb** [comment]
@zvonimir Yes, I do. It's embarrassing :-)

I will update the description.

**Comment by akashlal** [comment]
Can you tell me more about this feature?

**Comment by zvonimir** [comment]
Coming back to this. The idea of continuous integration is that regression tests are automatically run after every commit (for example). If anything fails, then alarms are raised, in the form of for example emails being sent to people in charge. We use continuous integration to some extent in SMACK, and we have some limited success in preventing stupid bugs from creeping into the main repo. If you wish, we can help to try to set this up for Corral.

**Comment by Guoanshisb** [comment]
@akashlal @zvonimir @shuvendu-lahiri It would be very useful if we want to merge smack-inst branch into main branch. But the first thing to do is to find regression to drive continuous integration :-)

**Comment by zvonimir** [comment]
Corral already has regressions, no?

**Comment by Guoanshisb** [comment]
@zvonimir Corral has regressions. It seems that smack-inst has not touched Corral. We need regressions for AV stuff (Avn, AvH, FastAvn, AA, etc.).

**Comment by shaobo-he** [comment]
Going back to this, @akashlal I'd like to take over this task. Could you add me to the administrators of Corral repo?

**Comment by zvonimir** [comment]
Corral now has CI up and running. Closing this.
