### ISSUE TITLE
Corral fails to take into account /bopt:proverOpt:OPTIMIZE_FOR_BV=true

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/corral#63]
I just realized that passing `/bopt:proverOpt:OPTIMIZE_FOR_BV=true` to Corral does not have the same effect as passing `/proverOpt:OPTIMIZE_FOR_BV=true`. In particular, it seems that Corral disregards this option and does not update the Z3 options the same way that Boogie does.
It would be great if Corral would have the same behavior as Boogie when this option is passed in.

**Comment by akashlal** [comment]
Can you say more: how are you running Corral?

When I do `corral.exe 001.bpl /proverOpt:OPTIMIZE_FOR_BV=true` then I get an error message `Usage error: Invalid flag: /proverOpt:OPTIMIZE_FOR_BV=true`. I checked: Corral doesn't accept a flag `/proverOpt`.

**Comment by zvonimir** [comment]
I run Corral with `/bopt:proverOpt:OPTIMIZE_FOR_BV=true`. I add `/bopt` since `proverOpt` is a Boogie command line option.

**Comment by zvonimir** [comment]
You are right. I have no idea what I was doing not to observe the same effect. This seems to be working fine. I am sorry for the trouble.

**Comment by zvonimir** [comment]
Here is something interesting I just realized with @liammachado's help. It is not causing problems for us, but maybe it is worth remembering.
On Linux, Corral is totally happy to run this even though it contains a totally bogus command line option - the program gets verified and no exception is thrown:
```
corral foo.bpl  /bopt:abcdef
```
On Windows, it will throw an exception.
So it seems there is some weird Windows/Linux discrepancy here. I have no idea why it is happening.

**Comment by zvonimir** [comment]
Ok, I get it now and I'll create a pull request for a fix. See this line in Boogie:
https://github.com/boogie-org/boogie/blob/master/Source/Core/CommandLineOptions.cs#L342
Under Linux, path separator is indeed `/`, and hence Boogie will treat anything that starts with `/` as a file name (if it is not a valid command line option). Hence, invoking Corral with `corral foo.bpl  /bopt:abcdef` will happily go through.
The solution is not to prefix `bopt` options with `/` but instead with `-`, which should have the same effect but will avoid this path name confusion.
