### ISSUE TITLE
AV: $CurrAddr shows up in blocking expression

### ISSUE THREAD

**Issue by Guoanshisb** [boogie-org/corral#7]
https://github.com/boogie-org/corral/blob/smack-inst/AddOns/AngelicVerifierNull/test/c-smack/link-list-test.bpl

EE fails because `$CurrAddr` shows up in blocking expression where it should not be.

**Comment by shuvendu-lahiri** [comment]
We need to understand better what causes $currAddr to even show up in the block expression. Shaobo: can you get us a simpler repro?

**Comment by shuvendu-lahiri** [comment]
As Shaobo mentioned, it is likely due to malloc being inlined. we may have to stub the malloc functions and put the allocator attribute.

**Comment by akashlal** [comment]
Its not due to malloc getting inlined. Its not specific to SMACK either. It also shows up in SDV/AV, except that we use the (conservative) flag /blockOnFreeVars that suppresses the assertion when a free variable is encountered. This is why we haven't seen this in practice.

Looks like a fundamental issue. I need to think more about it.

**Comment by shuvendu-lahiri** [comment]
@Akash: I still do not understand the need for the conservative flag. If malloc is a stub that does not return scalar, then the return is considered an unknown which will be compared with the input parameter in the example above (Shaobo's checkin). I would expect EE to infer the non-aliasing constraint then, without referring to $currAddr.

**Comment by akashlal** [comment]
@shuvendu-lahiri You are right. My bad. I had forgotten about the flag /unknownProc:malloc. (We have too many flags!) 

From what I see in the BPL, the malloc procedure is not inlined. I think its just that we didn't anticipate malloc having a body. I'll take a look.

**Comment by akashlal** [comment]
Fixed. Regression t20 now reports a block and no bugs:
```
[TAG: AV_OUTPUT] ----- Analyzing t20.harness.bpl ------
[TAG: AV_OUTPUT] EXPLAINERROR-BLOCK :: (forall x_2: int, x_3: int :: unknownTrig
ger_2(x_2) && unknownTrigger_0(x_3) ==> x_2 != x_3)
```
