### ISSUE TITLE
AV: Null dereference

### ISSUE THREAD

**Issue by rcastano** [boogie-org/corral#71]
The following input causes a null dereference. The type alias seems to trigger the bug.
```
type Union;
type Ref = Union;

const unique r1 : Ref;
const unique null : Ref;
var m : [Ref] Ref;

procedure Foo(r : Ref) {
  assert m[r] != r1;
}
```

Steps:
1) Run `AvHarnessInstrumentation\bin\De
bug\AvHarnessInstrumentation.exe .\type_alias.bpl type_alias_hinst.bpl /traceSlicing`
2) Run `AngelicVerifierNull.exe .\type_alias_hinst.bpl /traceSlicing`

**Comment by shuvendu-lahiri** [comment]
Looks ok to me. Closing. @akashlal @rcastano
