### ISSUE TITLE
AV property files cannot refer to undeclared functions and variables

### ISSUE THREAD

**Issue by shuvendu-lahiri** [boogie-org/corral#75]
Example:

https://github.com/boogie-org/corral/blob/master/AddOns/PropInst/PropInst/ExampleProperties/probeBeforeUse-onlyProbed.avp 

with 

https://github.com/boogie-org/corral/tree/master/AddOns/AngelicVerifierNull/test/propinst-regressions/probe0.bpl

**Comment by shuvendu-lahiri** [comment]
@akashlal Please close the issue if the fix looks ok. Regressions pass.

**Comment by akashlal** [comment]
Looks fine
