### ISSUE TITLE
Command line option descriptions?

### ISSUE THREAD

**Issue by bitcalc** [boogie-org/corral#83]
Hi,

I'm new to Corral, and I want to understand Corral command line options defined in the [Configs.cs](https://github.com/boogie-org/corral/blob/master/source/Configs.cs) file. Is there any documentation for them? For example, I'd like to see the output to Z3, but /printFinalProg:1 doesn't work. :)

**Comment by akashlal** [comment]
The relevant option is `/proverLog:filename`.

(Closing, because I assume you already figured it out.)
