### ISSUE TITLE
Z3 fixedpoint module and its usage in Boogie/Corral

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/corral#88]
We run into an issue related to Boogie/Corral trying to use Z3's fixedpoint module: https://github.com/smackers/smack/issues/425

First of all, it seems that newer versions of Z3 replaced fixedpoint module with fp module. So maybe Boogie/Corral should be updated accordingly.

Second, it is unclear to us when (and why) do Boogie/Corral use this module. We failed to reproduce the problem and we also could not find where in the Boogie/Corral source code that module gets enabled. It would be great if you could shed some light on this.

**Comment by akashlal** [comment]
The fixedpoint module was used for the Duality algorithm (an alternative to
Corral's Stratified Inlining algorithm). It gets activated with the
/useDuality flag, which then triggers this code in BoogieVerify:

CommandLineOptions.Clo.FixedPointMode =
CommandLineOptions.FixedPointInferenceMode.Corral;CommandLineOptions.Clo.FixedPointEngine
= "duality";
vcgen = new Microsoft.Boogie.FixedpointVC(program,
CommandLineOptions.Clo.SimplifyLogFilePath,
CommandLineOptions.Clo.SimplifyLogFileAppend, new List<Checker>(),
options.extraRecBound);


You are getting an error even without using this flag?

Akash

**Comment by zvonimir** [comment]
Thanks Akash. We are still trying to root cause it. I'll let you know once we get to the bottom of this.

**Comment by shuvendu-lahiri** [comment]
@akashlal how difficult is it to revive this mode to target the new fixed point engine in Z3 with spacer (not sure if it is the same as the z3 fp)?

**Comment by akashlal** [comment]
@shuvendu-lahiri Duality triggers a different algorithm (not stratified inlining any more) that is implemented in Microsoft.Boogie.FixedpointVC. I am unsure of the status of that implementation.

**Comment by zvonimir** [comment]
This does not seem to be an issue any more. Closing it.
