### ISSUE TITLE
AV: False atoms not filtered

### ISSUE THREAD

**Issue by Guoanshisb** [boogie-org/corral#9]
For [**link-list-test.bpl**](https://github.com/boogie-org/corral/blob/smack-inst/AddOns/AngelicVerifierNull/test/c-smack/link-list-test.bpl), EE generates the following block expression,

`[TAG: AV_OUTPUT] EXPLAINERROR-BLOCK :: (forall x_3: int, x_4: int, x_2: int :: unknownTrigger_15(x_3) && unknownTrigger_0(x_4) && unknownTrigger_14(x_2) ==> !((x_3 == x_4 + 8 + 8 && x_4 + 8 == NULL) || (x_3 == x_4 + 8 && x_4 + 8 == NULL) || (x_3 == x_4 && x_2 == NULL) || $M.0[x_3] == NULL))`

`unknownTrigger_0` corresponds to the return value of `malloc` and `malloc` calls `$alloc`, in which `$CurrAddr` is assumed to be positive and assigned to the return value. Therefore, `x_4 + 8` should be false.

**Comment by Guoanshisb** [comment]
[ee1.txt](https://github.com/boogie-org/corral/files/256095/ee1.txt)

**Comment by shuvendu-lahiri** [comment]
We have realized that our current technique does not filter true/false atoms involving returns of stubs, as we assign fresh variables to them. E.g. x = foo(); --> {x = foo(); x = alloc_1;} which removes dependency on foo(). Perhaps we can add an assume == alloc_1 after x = foo().

**Comment by akashlal** [comment]
I don't follow. We'll need to discuss this. Ping me on skype.

**Comment by shuvendu-lahiri** [comment]
In fact, I realize that the only atoms e that we filter are those that Axioms |= e. It does not take into account any preconditions or even the body of the procedure. So the proposed fixed above does not help.

**Comment by shuvendu-lahiri** [comment]
We will instead fix this by reinstating the code that greedily drops clauses from the final CNF blocking clause.

**Comment by shuvendu-lahiri** [comment]
The issue should be fixed now. Test instruction in the fix.
