### ISSUE TITLE
Unable to run corral.exe on Mac

### ISSUE THREAD

**Issue by shazqadeer** [boogie-org/corral#93]
I built Corral using Visual Studio normally on my MacOS machine.

1. corral.exe was generated in corral/bin/Debug/ but it did not have executable permission set.
2. I manually did "chmod 755 corral.exe" and then attempted to run it but got the message "cannot execute binary file".

**Comment by shazqadeer** [comment]
My mistake.  I forgot that Corral (unlike Boogie) has not been ported to .NET core.  I have to use mono to run corral.exe.  

@michaelemmi: Any plans to port Corral to .NET Core?

**Comment by akashlal** [comment]
@shazqadeer Hopefully Mike's recent commit helps. See #91
