### ISSUE TITLE
Printing variable values

### ISSUE THREAD

**Issue by prgantonino** [boogie-org/corral#95]
Hi all,

First of all, thanks for such a great tool!

I am using corral to do some verification and was wondering if I could get the value of some variable printed in the counter example (Mainly call arguments). Maybe I can do this using some language attribute?

I have tried using the /printDataValues:1 flag but it hasn't changed the  counter example I am getting from corral.

Thanks a lot in advance,

Pedro

**Comment by akashlal** [comment]
Thanks for your interest @prgantonino. We should document this someplace, but roughly this is what you need to do.

First, declare a procedure (without an implementation) whose name starts with `boogie_si_record` and takes one parameter of the type that you want to print. For example:
```
procedure boogie_si_record_int(x:int);
```
Next, if you want to print the value of a variable `y` at some place in the program, then insert this statement at that point:
```
call {:cexpr "y"} boogie_si_record_int(y);
```

Finally, when you run corral with `/printDataValues:1` and it produces a trace, then any time the trace goes through a call to a `boogie_si_record` procedure, it will print the value of the expression (e.g. you will see something like `y = 12` if `y` has the value `12` along the trace).

Hope this helps.

**Comment by akashlal** [comment]
Closing.
