### ISSUE TITLE
question on exists clause

### ISSUE THREAD

**Issue by muyaview** [boogie-org/corral#97]
For below codes:
```c
procedure {:entrypoint} main()
{
    var arr: [int]int;

    arr[3] := 0;
    arr[0] := 1;
    arr[1] := 1;
    arr[2] := 1;

    assert(exists n:int :: n>=0 && n < 4 ==> arr[n] == 0);
}
```
arr[3] is assigned before other elements. The assertion got failed. 
However if arr[3] was assigned after arr[2] like below codes, the assertion would be passed. 
```c
procedure {:entrypoint} main()
{
    var arr: [int]int;

    arr[0] := 1;
    arr[1] := 1;
    arr[2] := 1;
    arr[3] := 0;

    assert(exists n:int :: n>=0 && n < 4 ==> arr[n] == 0);
}
```
Don't understand how does the assertion failure for the first case happen. Please help

**Comment by zvonimir** [comment]
This has been answered. I am closing it.
