### ISSUE TITLE
Handling stubs with modifies 

### ISSUE THREAD

**Issue by shuvendu-lahiri** [boogie-org/corral#98]
I did not realize that Corral ignores modifies on stubs (the first assert does not fail), but interestingly fails the assert when I uncomment the ensures clause on B. I would have thought that the ensures without the modifies will lead to an inconsistency (since x is 0 at start of B). Not sure if it is a feature/bug?

**dotnet corral.dll /recursionBound:18 /k:1 /tryCTrace /printDataValues:1 a.bpl**

```
var x: int;

procedure {:entrypoint} A() {
   x := 0;
   call B();
   assert (x == 0);
   call C();
   //assert (x == 0);
}

procedure B();
modifies x;
//ensures x > 1;

procedure C() 
{
  havoc x;
}
```

**Comment by akashlal** [comment]
Looks like a bug. Corral should not ignore the modifies clause.

**Comment by akashlal** [comment]
Fixed.
